var arr = [	"What if we could only talk in rhymes and meter?",
			"What if you could live anywhere in the world? Where would you live?",
			"What if you found out your house was infested with snakes?",
			"What if you had a money tree growing in your backyard?",
			"What if you had the chance to write a best-selling novel? Would it be a romance, mystery, or factual historical account?",
			"What if you were excellent at a sport? Which sport would you choose and why?",
			"What if you could do one thing so well you could be famous? What would you do?",
			"What if you could have any job you wanted?",
			"What if you could invent a new food? What would it taste like?",
			"What if you could marry someone famous, either living or dead?",
			"What if you could only wear one color the rest of your life? Which color would you choose and why?",
			"What if you lost everything tomorrow? Who would you run to for comfort?",
			"What if you never had to work again? Would you? What would you do?",
			"What if you could send a short message to the entire world? What would you say?",
			"What if you could start your life all over? What would you do differently?",
			"What if you could watch a movie about everything that happened in your life until now? Would you enjoy it?",
			"What if you had a friend that you spoke to the same way you speak to yourself? Would that friend stay your friend?",
			"What if you had to teach someone one thing? What would you teach?",
			"What if you could change one thing about yourself? What would you change?",
			"What if you dropped everything to pursue your dreams?",
			"What if you had to choose between a wonderful romantic spouse to whom you would be married for only a few years or a boring, unromantic spouse for your entire life? Which would you choose and why?",
			"What if you used every moment of your life productively?",
			"What if you had to choose between money or no love or love and no money? Which would you choose and why?",
			"What if you had to give up your sight or your hearing? Which would you choose and why?",
			"What if you were at a bank and robbers came in?",
			"What if you could live for 200 years?",
			"What if you could stop time whenever you wanted to?",
			"What if you could be any animal?",
			"What if you could change one thing about your past?",
			"What if you could post something on the Internet to make you famous overnight?",
			"What if you could only eat pizza the rest of your life? (or any other food)",
			"What if you found a way to get really rich very quickly that was illegal?",
			"What if you could walk on the ceiling?",
			"What if you had to choose between great wealth or great wisdom?",
			"What if you switched places with your pet?",
			"What if you have to sacrifice yourself for the sake of someone you love?",
			"What if you woke up in the morning with a stranger next to you in bed?",
			"What if you saw someone come out of a public toilet with paper stuck on their shoe?",
			"What if a turtle didn’t have his shell? Would he be homeless or naked?",
			"What if you saw someone steal from the place where you work?",
			"What if cats could bark and dogs meow?",
			"What if you were given the opportunity to mold your spouse or partner the way you wanted?",
			"What if you could fly?",
			"What if aliens landed in your back yard?",
			"What if you could have free, unlimited service for five years from an extremely good cook, a handsome chauffeur, or daily house cleaner? Which would you choose?",
			"What if you could never eat your favorite food again in your life?",
			"What if you were a type of candy? What candy would you be?",
			"What if you could only live somewhere that was always above 100 degrees? Always below freezing?",
			"What if you were a tree? What would you say to those who walk by?",
			"What if you discovered you could heal diseases?",
			"What if you were a monster? What monster would you choose to be?",
			"What if you found a million dollars?",
			"What if you could only walk on your hands?",
			"What if you found out your spouse had another family in another state?",
			"What if you could talk to animals? What would you say or ask?",
			"What if you had three wishes? What would you wish for?",
			"What if you had a tail?",
			"What if you had to lose a body part? Which would you choose to give up and why?",
			"What if you lost your bathing suit while you were swimming, what would you do?",
			"What if you woke up with a dead stranger next to you?",
			"What if you woke up one morning to find you had switched bodies and families with your best friend?",
			"What if cats could swim under water?",
			"What if you woke up tomorrow morning and could only hop everywhere you went?",
			"What if you could change your appearance? What would you choose to look like?",
			"What if you could have any one supernatural power (reading minds, great strength, flying, or being invisible)? Which would you choose and why?",
			"What if you had to live one day over and over again? What would your chosen day be like?",
			"What if you could only wear one set of clothes for the rest of your life? What would you choose to wear and why?",
			"What if you went for a walk in the woods and found a money tree?",
			"What if you found out you were really a robot?",
			"What if you woke up and were twenty years younger? Older?",
			"What if you were a fruit? What fruit would you choose to be and why?",
			"What if a ghost haunted your bedroom at night?",
			"What if your body was a bright color? Which color would you choose and why?",
			"What if I you died right now?",
			"What if you could neglect one personal hygiene routine (shaving, brushing your teeth, cutting your nails, etc.) without any adverse effect to your image or health? Which would you choose and why?",
			"What if you could travel back in time?",
			"What if you used a public toilet and discovered there was no paper?",
			"What if you had to choose between fame and fortune?",
			"What if you were allowed to eat only one food for the rest of your life? Which food would you choose and why?",
			"What if you were alone at home and you heard footsteps coming up your stairs?",
			"What if you woke up in bed and saw spiders walking all over you?",
			"What if you found a wallet with $10,000 in it?",
			"What if your cell phone fell in the toilet?",
			"What if you could change one thing about the person you love? What would it be?",
			"What if you could live under water because you had gills?",
			"What if you could read minds?",
			"What if you hit a car in a parking lot, but nobody saw you do it?",
			"What if you knew you had only 24 hours to live?",
			"What if you could choose how you were going to die?",
			"What if you were chosen to go into space?",
			"What if you were dreaming about your teeth falling out, and you woke up to find that they had?"];

var arrAra = [	"ماذا لو استطعنا التحدث فقط في القوافي والمتر؟" ,
				"ماذا لو كنت تستطيع العيش في أي مكان في العالم؟ أين ستعيش؟" ,
				"ماذا لو اكتشفت أن منزلك مليء بالثعابين؟" ,
				"ماذا لو كان لديك شجرة مال تنمو في فنائك الخلفي؟" ,
				"ماذا لو أتيحت لك الفرصة لكتابة رواية مبيعا؟ هل ستكون قصة حب ، أو سر ، أو قصة تاريخية واقعية؟" ,
				"ماذا لو كنت ممتازًا في الرياضة؟ ما الرياضة التي ستختارها ولماذا؟" ,
				"ماذا لو كنت تستطيع أن تفعل شيئًا واحدًا جيدًا يمكنك أن تكون مشهورًا؟ ماذا ستفعل؟" ,
				"ماذا لو كان لديك أي وظيفة تريدها؟" ,
				"ماذا لو استطعت ابتكار طعام جديد؟ كيف سيكون مذاقه؟" ,
				"ماذا لو كان بإمكانك الزواج من شخص مشهور ، سواء كان حيًا أو ميتًا؟" ,
				"ماذا لو كان بإمكانك ارتداء لون واحد فقط لبقية حياتك؟ ما اللون الذي ستختاره ولماذا؟" ,
				"ماذا لو فقدت كل شيء غدًا؟ إلى من ستهرب للراحة؟" ,
				"ماذا لو لم تضطر إلى العمل مرة أخرى؟ هل ستفعل؟ ماذا ستفعل؟" ,
				"ماذا لو كان بإمكانك إرسال رسالة قصيرة إلى العالم بأسره؟ ماذا ستقول؟" ,
				"ماذا لو استطعت أن تبدأ حياتك من جديد؟ ماذا ستفعل بشكل مختلف؟" ,
				"ماذا لو كنت تستطيع مشاهدة فيلم عن كل ما حدث في حياتك حتى الآن؟ هل تستمتع به؟" ,
				"ماذا لو كان لديك صديق تحدثت معه بنفس الطريقة التي تتحدث بها إلى نفسك؟ هل سيبقى هذا الصديق صديقك؟" ,
				"ماذا لو كان عليك أن تعلم شخصًا واحدًا؟ ماذا ستعلم؟" ,
				"ماذا لو كنت تستطيع تغيير شيء واحد عن نفسك؟ ماذا ستغير؟" ,
				"ماذا لو أسقطت كل شيء لتحقيق أحلامك؟" ,
				"ماذا لو كان عليك أن تختار بين زوج رومانسي رائع ستتزوجه لبضع سنوات فقط أو زوج ممل وغير رومانسي طوال حياتك؟ أيهما تختار ولماذا؟" ,
				"ماذا لو استخدمت كل لحظة من حياتك بشكل منتج؟" ,
				"ماذا لو كان عليك الاختيار بين المال أو لا حب أو حب ولا مال؟ أيهما ستختار ولماذا؟" ,
				"ماذا لو اضطررت للتخلي عن نظرك أو سمعك؟ أيهما ستختار ولماذا؟" ,
				"ماذا لو كنت في البنك ودخل اللصوص؟" ,
				"ماذا لو كنت تستطيع العيش لمدة 200 عام؟" ,
				"ماذا لو كنت تستطيع التوقف عن الوقت كلما أردت؟" ,
				"ماذا لو كنت تستطيع أن تكون أي حيوان؟" ,
				"ماذا لو كنت تستطيع تغيير شيء واحد عن ماضيك؟" ,
				"ماذا لو كان بإمكانك نشر شيء على الإنترنت لجعلك مشهورًا بين عشية وضحاها؟" ,
				"ماذا لو كنت تستطيع أن تأكل البيتزا فقط بقية حياتك؟ (أو أي طعام آخر)" ,
				"ماذا لو وجدت طريقة للثراء بسرعة كبيرة وكان ذلك غير قانوني؟" ,
				"ماذا لو استطعت المشي على السقف؟" ,
				"ماذا لو كان عليك الاختيار بين ثروة عظيمة أو حكمة عظيمة؟" ,
				"ماذا لو بدلت الأماكن مع حيوانك الأليف؟" ,
				"ماذا لو كان عليك أن تضحي بنفسك من أجل شخص تحبه؟" ,
				"ماذا لو استيقظت في الصباح مع شخص غريب بجانبك في السرير؟" ,
				"ماذا لو رأيت شخصًا يخرج من المرحاض العام مع ورق عالق على حذائه؟" ,
				"ماذا لو لم تمتلك السلحفاة قوقعته؟ هل سيكون بلا مأوى أم عاري؟" ,
				"ماذا لو رأيت شخصًا يسرق من مكان عملك؟" ,
				"ماذا لو كانت القطط تنبح والكلاب مواء؟" ,
				"ماذا لو أتيحت لك الفرصة لتشكيل زوجك أو شريكك بالطريقة التي تريدها؟" ,
				"ماذا لو استطعت الطيران؟" ,
				"ماذا لو هبط الأجانب في ساحتك الخلفية؟" ,
				"ماذا لو كان بإمكانك الحصول على خدمة مجانية غير محدودة لمدة خمس سنوات من طاهي جيد للغاية ، أو سائق وسيم ، أو منظف يومي للمنزل؟ أيهما ستختار؟" ,
				"ماذا لو لم تستطع تناول طعامك المفضل مرة أخرى في حياتك؟" ,
				"ماذا لو كنت من نوع الحلوى؟ ما هي الحلوى التي ستكونها؟" ,
				"ماذا لو كنت تستطيع العيش في مكان ما كان دائمًا أعلى من 100 درجة؟ دائمًا أقل من درجة التجمد؟" ,
				"ماذا لو كنت شجرة؟ ماذا ستقول لأولئك الذين يمرون؟" ,
				"ماذا لو اكتشفت أنه يمكنك شفاء الأمراض؟" ,
				"ماذا لو كنت وحشًا؟ أي وحش ستختار أن تكون؟" ,
				"ماذا لو وجدت مليون دولار؟" ,
				"ماذا لو كنت تستطيع المشي فقط على يديك؟" ,
				"ماذا لو اكتشفت أن زوجتك لديها عائلة أخرى في دولة أخرى؟" ,
				"ماذا لو كنت تستطيع التحدث إلى الحيوانات؟ ماذا تقول أو تسأل؟" ,
				"ماذا لو كان لديك ثلاث رغبات؟ ماذا تتمنى؟" ,
				"ماذا لو كان لديك ذيل؟" ,
				"ماذا لو كان عليك أن تفقد جزءًا من الجسم؟ أيهما تختار أن تتخلى عنه ولماذا؟" ,
				"ماذا لو فقدت ثوب السباحة الخاص بك أثناء السباحة ، ماذا ستفعل؟" ,
				"ماذا لو استيقظت مع شخص غريب ميت بجانبك؟" ,
				"ماذا لو استيقظت ذات صباح لتجد أنك بدلت الجثث والعائلات مع أفضل صديق لك؟" ,
				"ماذا لو كانت القطط تسبح تحت الماء؟" ,
				"ماذا لو استيقظت صباح الغد ولم تستطيعي القفز إلا في كل مكان ذهبت إليه؟" ,
				"ماذا لو كان بإمكانك تغيير مظهرك؟ كيف تختار أن تبدو؟" ,
				"ماذا لو كان بإمكانك الحصول على أي قوة خارقة للطبيعة (قراءة العقول ، أو قوة كبيرة ، أو الطيران ، أو كونها غير مرئية)؟ ما الذي ستختاره ولماذا؟" ,
				"ماذا لو كان عليك أن تعيش يوما ما مرارا وتكرارا؟ كيف سيكون يومك المختار؟" ,
				"ماذا لو كان بإمكانك ارتداء مجموعة واحدة من الملابس لبقية حياتك؟ ماذا تختار أن ترتدي ولماذا؟" ,
				"ماذا لو ذهبت في نزهة في الغابة ووجدت شجرة المال؟" ,
				"ماذا لو اكتشفت أنك حقًا روبوت؟" ,
				"ماذا لو استيقظت وكنت أصغر بعشرين سنة؟ أكبر؟" ,
				"ماذا لو كنت فاكهة؟ ما الفاكهة التي تختار أن تكون ولماذا؟" ,
				"ماذا لو طارد شبح غرفة نومك في الليل؟" ,
				"ماذا لو كان جسمك ذا لون مشرق؟ أي لون ستختار ولماذا؟" ,
				"ماذا لو مت الآن؟" ,
				"ماذا لو كنت تهمل روتينًا واحدًا للنظافة الشخصية (الحلاقة ، تنظيف الأسنان ، قطع أظافرك ، وما إلى ذلك) دون أي تأثير سلبي على صورتك أو صحتك؟ ما الذي ستختاره ولماذا؟" ,
				"ماذا لو كنت تستطيع السفر في الوقت المناسب؟" ,
				"ماذا لو استخدمت مرحاض عام واكتشفت أنه لا يوجد ورق؟" ,
				"ماذا لو كان عليك الاختيار بين الشهرة والثروة؟" ,
				"ماذا لو سمح لك بتناول طعام واحد فقط لبقية حياتك؟ أي طعام ستختار ولماذا؟" ,
				"ماذا لو كنت بمفردك في المنزل وسمعت خطى تصعد سلالمك؟" ,
				"ماذا لو استيقظت في السرير ورأيت العناكب تسير في جميع أنحاءك؟" ,
				"ماذا لو وجدت محفظة بها 10،000 دولار؟" ,
				"ماذا لو سقط هاتفك الخلوي في المرحاض؟" ,
				"ماذا لو كان بإمكانك تغيير شيء واحد عن الشخص الذي تحبه؟ ماذا سيكون؟" ,
				"ماذا لو كنت تستطيع العيش تحت الماء لأن لديك خياشيم؟" ,
				"ماذا لو كنت تستطيع قراءة العقول؟" ,
				"ماذا لو اصطدمت بسيارة في موقف للسيارات ، ولكن لا أحد رآك تفعل ذلك؟" ,
				"ماذا لو علمت أن لديك 24 ساعة فقط للعيش؟" ,
				"ماذا لو كان بإمكانك اختيار كيف ستموت؟" ,
				"ماذا لو تم اختيارك للذهاب إلى الفضاء؟" ,
				"ماذا لو كنت تحلم بتساقط أسنانك ، واستيقظت لتجد أن لديهم؟"];
var quesE = document.querySelector("#questionsEng");
var quesA = document.querySelector("#questionsArr");

var Eng = document.querySelector(".Eng");
var Ara = document.querySelector(".Ara");

var rand = Math.floor(Math.random() * arr.length);
changeLang(1);
function changeQues (lang){
	if(lang == 1)
	{
		Ara.style.display = "none";
		Eng.style.display = "block";
		quesE.innerHTML = arr[rand];
		rand = Math.floor(Math.random() * arr.length);
	} else {
		Eng.style.display = "none";
		Ara.style.display = "block";
		quesA.innerHTML = arrAra[rand];
		rand = Math.floor(Math.random() * arrAra.length);
	}
}

function changeLang (){
	var lang = document.querySelector('#lang').value;
	changeQues(lang);
}